--- 
Trivy_container_scanning: 
  allow_failure: true
  artifacts: 
    reports: 
      container_scanning: gl-container-scanning-report.html
  before_script: 
    - "export TRIVY_VERSION=${TRIVY_VERSION:-v0.19.2}"
    - "apk add --no-cache curl docker-cli"
    - "docker login -u \"$CI_REGISTRY_USER\" -p \"$CI_REGISTRY_PASSWORD\" $CI_REGISTRY"
    - "curl -sfL https://github.com/krishna-commits/trivy/blob/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${TRIVY_VERSION}"
    - "curl -sSL -o /tmp/trivy-html.tpl https://github.com/krishna-commits/trivy/blob/main/${TRIVY_VERSION}/contrib/html.tpl"
  cache: 
    paths: 
      - .trivycache/
  dependencies: []
  image: 
    name: "alpine:3.11"
  only: 
    refs: 
      - branches
  script: 
    - "trivy --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template \"@/tmp/trivy-html.tpl\" -o gl-container-scanning-report.html $IMAGE"
  stage: test
  variables: 
    GIT_STRATEGY: none
    IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
